// Generated by CoffeeScript 1.3.3
(function() {

  $(function() {
    var barWidth, data, maxCount, maxHeight, maxWidth, x, y;
    data = [
      {
        year: 2009,
        count: 50
      }, {
        year: 2010,
        count: 120
      }, {
        year: 2011,
        count: 70
      }, {
        year: 2012,
        count: 140
      }
    ];
    barWidth = 40;
    maxWidth = (barWidth + 10) * data.length;
    maxHeight = 250;
    maxCount = d3.max(data, function(d) {
      return d.count;
    });
    x = d3.scale.linear().domain([0, data.length]).range([0, maxWidth]);
    y = d3.scale.linear().domain([0, maxCount]).rangeRound([0, maxHeight]);
    return d3.select('svg').selectAll('rect').data(data).enter().append('svg:rect').attr('x', function(d, index) {
      return x(index);
    }).attr('y', function(d, index) {
      return maxHeight - y(d.count);
    }).attr('width', barWidth).attr('height', function(d) {
      return y(d.count);
    }).attr('fill', '#0C5682');
  });

}).call(this);
