// Generated by CoffeeScript 1.3.3
(function() {

  $(function() {
    var chart, data, height, next, redraw, t, v, width, x, y;
    t = 100000;
    v = 70;
    next = function() {
      return {
        time: ++t,
        value: v = ~~Math.max(10, Math.min(90, v + 10 * (Math.random() - .5)))
      };
    };
    data = d3.range(33).map(next);
    setInterval(function() {
      data.shift();
      data.push(next());
      return redraw();
    }, 1500);
    width = 20;
    height = 80;
    x = d3.scale.linear().domain([0, 1]).range([0, width]);
    y = d3.scale.linear().domain([0, 100]).rangeRound([0, height]);
    chart = d3.select('svg');
    chart.selectAll('rect').data(data).enter().append('svg:rect').attr('x', function(d, i) {
      return x(i) - .5;
    }).attr('y', function(d) {
      return height - y(d.value) - .5;
    }).attr('width', width).attr('height', function(d) {
      return y(d.value);
    }).attr('fill', '#0C5682').attr('stroke', 'white');
    return redraw = function() {
      var rect;
      rect = chart.selectAll('rect').data(data, function(d) {
        return d.time;
      });
      rect.enter().append('svg:rect').attr('x', function(d, i) {
        return x(i + 1) - .5;
      }).attr('y', function(d) {
        return height - y(d.value) - .5;
      }).attr('width', width).attr('height', function(d) {
        return y(d.value);
      }).attr('fill', '#0C5682').attr('stroke', 'white').transition().duration(1000).attr('x', function(d, i) {
        return x(i) - .5;
      });
      rect.transition().duration(1000).attr('x', function(d, i) {
        return x(i) - .5;
      });
      return rect.exit().transition().duration(1000).attr('x', function(d, i) {
        return x(i - 1) - .5;
      }).remove();
    };
  });

}).call(this);
