$ ->
  d3.select('#container')
    .append('svg:svg')
    .attr('width', 600)
    .attr('height', 600)

  d3.select('svg')
    .append('svg:rect')
    .attr('x', 40)
    .attr('y', 60)
    .attr('width', 160)
    .attr('height', 70)

  d3.select('svg')
    .append('svg:circle')
    .attr('cx', 210)
    .attr('cy', 310)
    .attr('r', 60)
    .attr('fill', 'red')
    
  d3.select('svg')
    .append('svg:ellipse')
    .attr('cx', 310)
    .attr('cy', 110)
    .attr('rx', 60)
    .attr('ry', 30)
    .attr('fill', 'blue')
